excluded: # paths to ignore during linting. Takes precedence over `included`.
  - WeatherManager/AppResources/R/R.generated.swift
disabled_rules:
  - colon
  - nesting
  - opening_brace
  - function_body_length
  - function_parameter_count
  - vertical_whitespace
  - trailing_whitespace
  - trailing_comma
  - trailing_newline
  - generic_type_name
  - identifier_name
  - type_name
  - line_length
  - cyclomatic_complexity
  - closure_parameter_position
  - force_cast
  - large_tuple
